apiVersion: v1 
kind: Pod

metadata: 
  name: annotations
  labels:
    project: roboshop
    environment: dev
  annotations:
    description: "this pod is created to demonstrate pod annotation"
    jenkins: "https://jenkins.com/build/job/roboshop-catalogue/3"
  
spec:
  containers:
  - name: nginx
    image: nginx    