apiVersion: v1
kind: Service

metadata: 
  name : nginx-LB
  labels:
    purpose: service-LB-demonstrate
  
spec: 
  type: LoadBalancer
  selector: 
    purpose: service-demo-LB
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-LB
  labels: 
    purpose: service-demo-LB
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx